
import { SignOutButton } from "@clerk/clerk-react";
import { SignIn, SignInButton, SignedOut, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";



const Home: NextPage = () => {
  const user = useUser();

  const { data: postData } = api.posts.getAll.useQuery();
  const { data: userData } = api.users.getAll.useQuery();
  const { data: coterieData } = api.coteries.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          {postData?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
        <div>
          {userData?.map((user) => (
            <div key={user.id}>{user.id}</div>
          ))}
        </div>
        <div>
          {coterieData?.map((coterie) => (
            <div key={coterie.id}>{coterie.name}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
